experiment_name: NBAGames
model_name: bayesian_model

inputs_team:
# - away_season_wins_avg
# - home_season_wins_avg
# - away_season_pts_diff_avg
# - home_season_pts_diff_avg
- away_last_5_pts_diff_avg
- home_last_5_pts_diff_avg
target:
- final_score_diff

data_params:
  seasons: 2
  seed: 66
  test_size: 0.2
  n: 20
  frac: null

training:
  params:
    learning_rate: 0.05
    lr_gamma: 0.85
    batch_size: 128
    epochs: 80
    eval_freq: 1
    # L2 regularization to the model parameters
    weight_decay: 0.5
    weighted_loss: false
    clamp_var: null # 10
  model_config:
    embedding_dim: 4
    team_hidden_dim: 12 #8
    team_layers: 4 #2
    res_hidden_dim: 32
    res_layers: 2 # 2
    time_scaling:  true
