experiment_name: NBAGames-FINAL
model_name: lin_model
inputs_team:
- away_season_pts_diff_avg
- home_season_pts_diff_avg
- away_last_5_pts_diff_avg
- home_last_5_pts_diff_avg
target:
- final_score_diff
data_params:
  seasons: 2
  seed: 66
  test_size: 0.1
  'n': 15
  frac: null
  reserve_validation: false
training:
  algorithm: linear_regression
  params:
    alpha: 99.94523496627072
    random_state: 2
  model_config:
    include_teams: true
