experiment_name: NBAGames-FINAL
model_name: bayesian_model
inputs_team:
- away_season_pts_diff_avg
- home_season_pts_diff_avg
- away_last_5_pts_diff_avg
- home_last_5_pts_diff_avg
target:
- final_score_diff
data_params:
  seasons: 2
  seed: 66
  test_size: 0.1
  'n': 15
  frac: null
  reserve_validation: false
training:
  algorithm: bayesian_nn
  params:
    learning_rate: 0.002178737122149179
    lr_gamma: 0.8354521167934316
    batch_size: 128
    epochs: 80
    eval_freq: 1
    weight_decay: 1.2171989575527562e-06
    weighted_loss: false
    seed: 5
  model_config:
    embedding_dim: null
    team_hidden_dim: 4
    team_layers: 3
    res_hidden_dim: 22
    res_layers: 2
