experiment_name: NBAGames-FINAL
model_name: cb_model
inputs_team:
- away_season_pts_diff_avg
- home_season_pts_diff_avg
- away_last_5_pts_diff_avg
- home_last_5_pts_diff_avg
target:
- final_score_diff
data_params:
  seasons: 2
  seed: 66
  test_size: 0.1
  'n': 15
  frac: null
  reserve_validation: false
training:
  algorithm: catboost_regressor
  params:
    learning_rate: 0.09636223593149941
    random_state: 47
    colsample_bylevel: 0.9433600798423123
    subsample: 0.5369048376010586
    max_bin: 91
    max_depth: 5
    loss_function: RMSEWithUncertainty
    task_type: CPU
    iterations: 1400
    boosting_type: Plain
    bootstrap_type: Bernoulli
    verbose: 500
    l2_leaf_reg: 0.4290344235973468
  model_config:
    include_teams: true
    unify_home_away: true
inputs_numeric:
- avg_points_team_A
- avg_fg_pct_team_A
- avg_three_point_pct_team_A
- avg_ft_pct_team_A
- avg_rebounds_team_A
- avg_assists_team_A
- avg_steals_team_A
- avg_blocks_team_A
- avg_points_team_B
- avg_fg_pct_team_B
- avg_three_point_pct_team_B
- avg_ft_pct_team_B
- avg_rebounds_team_B
- avg_assists_team_B
- avg_steals_team_B
- avg_blocks_team_B
